variables:
    DJANGO_VERSION: ">=1.10,<1.11.99"
    # Add path to the IDL directory
    PYTHONPATH: "idl"

stages:
    - analysis
    - test
    - coverage

########################################################################################################################
# Basic declarations
.requires-python: &requires-python
    tags:
        - python

.python2-xenial: &python2-xenial
    image: cznic/ubuntu_xenial_python2:latest

.install-dependencies: &install-dependencies
    before_script:
        - pip list
        # Install package dependencies
        - apt-get update && apt-get install -y omniidl-python python-omniorb
        # Get pr-version and update requirements
        - git clone git@gitlab.office.nic.cz:pr-utils/pr-version.git --depth 1
        - pervert-requirements.py
        - cat requirements.txt
        # Parse IDL requirements
        - if [ -e pr-version/devel/$CI_BUILD_REF_NAME.conf ]; then IDL_BRANCH=$(python -c "import json;obj=json.loads(open('pr-version/devel/${CI_BUILD_REF_NAME}.conf').read());print obj.get('idl',{}).get('revision', 'master')"); fi
        - git clone git@gitlab.office.nic.cz:fred/idl.git
        - (cd idl && git checkout $IDL_BRANCH && omniidl -bpython -Wbmodules=fred_idl -Wbstubs=fred_idl._stubs idl/*.idl)
        # Install dependencies
        - pip install django$DJANGO_VERSION
        - pip install -r requirements.txt $EXTRA_REQUIREMENTS
        - pip list

.test: &test
    <<: *requires-python
    <<: *python2-xenial
    <<: *install-dependencies
    stage: test
    script:
        - mkdir coverage
        - make test-coverage
    artifacts:
        expire_in: 1d
        paths:
        - coverage/
    variables:
        COVERAGE_FILE: "coverage/.coverage.$CI_BUILD_ID"
        EXTRA_REQUIREMENTS: "-r requirements-dev.txt coverage"

########################################################################################################################
# Individual jobs
isort:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install isort
        - pip list
    script: "make check-isort"

flake8:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install flake8
        - pip list
    script: "make check-flake8"

test:django1.10:
    <<: *test
    variables:
        COVERAGE_FILE: "coverage/.coverage.$CI_BUILD_ID"
        DJANGO_VERSION: ">=1.10,<1.10.99"
        EXTRA_REQUIREMENTS: "-r requirements-dev.txt coverage"

test:
    <<: *test

coverage-report:
    <<: *requires-python
    <<: *python2-xenial
    stage: coverage
    script:
        - pip install coverage
        - pip list
        - coverage combine coverage/
        - coverage report --include=*/tests/* --fail-under=100
        - coverage report --omit=*/tests/*
