before_script:
    - pip list

isort:
    image: cznic/ubuntu_python_runner:latest
    script: "make check-isort"

flake8:
    image: cznic/ubuntu_python_runner:latest
    script: "make check-flake8"

.test: &test
    image: cznic/ubuntu_python_runner:latest
    script:
        # Install omniORB and omniIDL
        - apt-get update && apt-get install -y python-omniorb omniidl-python
        # freddist are required to install our dependencies
        - pip install -e git+git@gitlab.office.nic.cz:utils/freddist.git#egg=freddist
        # Get prcal's last commit in master
        - git clone git@gitlab.office.nic.cz:utils/prcal.git --depth 1
        # Parse requirements with prcal library to add required branch dependencies
        - prcal.py
        # Parse IDL requirements
        - if [ -e prcal/devel/$CI_BUILD_REF_NAME.conf ]; then IDL_BRANCH=$(python -c "import json;obj=json.loads(open('prcal/devel/${CI_BUILD_REF_NAME}.conf').read());print obj.get('idl',{}).get('revision', 'master')"); fi
        # Control print of requirements
        - cat requirements.txt
        # IDL's are required for rdap
        - git clone git@gitlab.office.nic.cz:fred/idl.git
        - (cd idl && git checkout $IDL_BRANCH)
        - pip install django$DJANGO_VERSION
        - pip install --find-links=/usr/share/python-wheels -r requirements.txt
        - pip install --find-links=/usr/share/python-wheels -r requirements-dev.txt
        - pip list
        - make test

test:django1.7:
    <<: *test
    variables:
        DJANGO_VERSION: ">=1.7,<1.7.99"

test:django1.8:
    <<: *test
    variables:
        DJANGO_VERSION: ">=1.8,<1.8.99"

test:django1.9:
    <<: *test
    variables:
        DJANGO_VERSION: ">=1.9,<1.9.99"
