import os

INSTALLED_APPS = ()
ROOT_URLCONF = 'rdap.urls'
SECRET_KEY = 'SECRET'

CORBA_IDL_ROOT_PATH = os.environ.get('FRED_IDL_DIR', './idl/idl')
CORBA_IDL_LOGGER_FILENAME = 'Logger.idl'
CORBA_NS_HOST_PORT = 'localhost'
CORBA_NS_CONTEXT = 'fred'
RDAP_ROOT_URL = ''
DNS_MAX_SIG_LIFE = 1209600
DISCLAIMER_FILE = ''
UNIX_WHOIS_HOST = ''
